# Use examples of [edges](https://github.com/romainsacchi/edges)

Author: [romainsacchi](https://github.com/romainsacchi)

This notebook shows examples on how to use `edge` to use exchange-specific
characterization factors in the characterization matrix of `bw2calc`, combining the use of exchange names and locations.

## Requirements

* **Pyhton 3.10 or higher (up to 3.11) is highly recommended**

# Use case with [brightway2](https://brightway.dev/)

`brightway2` is an open source LCA framework for Python.
To use `premise` from `brightway2`, it requires that you have an activated `brightway2` project with a `biosphere3` database as well as an [ecoinvent](https://ecoinvent.prg) v.3 cut-off or consequential database registered in that project. Please refer to the brightway [documentation](https://brightway.dev) if you do not know how to create a project and install ecoinvent.

In [ ]:
from edges import EdgeLCIA, get_available_methods, setup_package_logging
import bw2data

In [2]:
bw2data.databases

Databases dictionary with 2 object(s):
	biosphere3
	ecoinvent-3.10.1-cutoff

One can simply build its own LCIA file.
Let's consider the following LCIA file (saved under `lcia_example_2.json`):

In [3]:
{
  "name": "Example LCIA Method",
  "version": "1.0",
  "description": "Example LCIA method for greenhouse gas emissions",
  "unit": "kg CO2e",
  "exchanges": [
    {
      "supplier": {
        "name": "Carbon dioxide",
        "operator": "startswith",
        "matrix": "biosphere"
      },
      "consumer": {
        "matrix": "technosphere",
        "location": "CH"
      },
      "value": 1.0
    },
    {
      "supplier": {
        "name": "Carbon dioxide",
        "operator": "startswith",
        "matrix": "biosphere"
      },
      "consumer": {
        "matrix": "technosphere",
        "location": "FR"
      },
      "value": 2.0
    },
    {
      "supplier": {
        "name": "Carbon dioxide",
        "operator": "startswith",
        "matrix": "biosphere"
      },
      "consumer": {
        "matrix": "technosphere",
        "location": "RER"
      },
      "value": 3.0
    },
    {
      "supplier": {
        "name": "Carbon dioxide",
        "operator": "startswith",
        "matrix": "biosphere"
      },
      "consumer": {
        "matrix": "technosphere",
        "location": "CA"
      },
      "value": 15
    }
  ]
}

{'name': 'Example LCIA Method',
 'version': '1.0',
 'description': 'Example LCIA method for greenhouse gas emissions',
 'unit': 'kg CO2e',
 'exchanges': [{'supplier': {'name': 'Carbon dioxide',
    'operator': 'startswith',
    'matrix': 'biosphere'},
   'consumer': {'matrix': 'technosphere', 'location': 'CH'},
   'value': 1.0},
  {'supplier': {'name': 'Carbon dioxide',
    'operator': 'startswith',
    'matrix': 'biosphere'},
   'consumer': {'matrix': 'technosphere', 'location': 'FR'},
   'value': 2.0},
  {'supplier': {'name': 'Carbon dioxide',
    'operator': 'startswith',
    'matrix': 'biosphere'},
   'consumer': {'matrix': 'technosphere', 'location': 'RER'},
   'value': 3.0},
  {'supplier': {'name': 'Carbon dioxide',
    'operator': 'startswith',
    'matrix': 'biosphere'},
   'consumer': {'matrix': 'technosphere', 'location': 'CA'},
   'value': 15}]}

In [4]:
bw2data.databases

Databases dictionary with 2 object(s):
	biosphere3
	ecoinvent-3.10.1-cutoff

In [5]:
# activate the bw project
act = bw2data.Database("ecoinvent-3.10.1-cutoff").random()
act

'copper production, cathode, solvent extraction and electrowinning process' (kilogram, GLO, None)

In [6]:
act

'copper production, cathode, solvent extraction and electrowinning process' (kilogram, GLO, None)

In [7]:
LCA = EdgeLCIA(
    demand={act: 1},
    method=("some", "method"),
    filepath="lcia_example_2.json"
)
LCA.lci()

LCA.map_exchanges()

LCA.evaluate_cfs()
LCA.lcia()
LCA.score

0.36503066041242166

### Generate dataframe of characterization factors used

The `generate_cf_table` method generates a dataframe of the characterization factors used in the calculation. One can see the characterization factors used for each exchange in the system. For deterministic regionalized runs, `split_aggregate_consumers=True` expands weighted fallback consumer regions such as RER, GLO, RoW, or RoE into country rows.

In [8]:
df = LCA.generate_cf_table(split_aggregate_consumers=True)

In [9]:
# we can see under the "CF" column
# the characterization factors used for each exchange in the system
df

,supplier name,supplier categories,consumer name,consumer reference product,consumer location,consumer cpc,consumer ecospold01categories,consumer isic rev.4 ecoinvent,amount,CF,impact
0,"Carbon dioxide, non-fossil, resource correction","(natural resource, in air)","sulfate pulp production, from hardwood, bleached","sulfate pulp, bleached",RER,"32112: Chemical wood pulp, other than dissolvi...",None,"1701:Manufacture of pulp, paper and paperboard",7.260190e-07,3.0,2.178057e-06
1,"Carbon dioxide, non-fossil, resource correction","(natural resource, in air)",glued solid timber production,"wood chips, dry, measured as dry mass",RER,31230: Wood in chips or particles,None,1621:Manufacture of veneer sheets and wood-bas...,1.480537e-04,3.0,4.441612e-04
2,"Carbon dioxide, non-fossil, resource correction","(natural resource, in air)","planing, board, hardwood, u=10%","shavings, hardwood, loose, measured as dry mass",CH,39283: Non-agglomerated wood waste and scrap,None,1610:Sawmilling and planing of wood,1.827733e-09,1.0,1.827733e-09
3,"Carbon dioxide, non-fossil, resource correction","(natural resource, in air)","planing, board, hardwood, u=10%","sawnwood, board, hardwood, dried (u=10%), planed",CH,"31102: Wood, sawn or chipped lengthwise, slice...",None,1610:Sawmilling and planing of wood,-4.806192e-11,1.0,-4.806192e-11
4,"Carbon dioxide, non-fossil, resource correction","(natural resource, in air)","sulfate pulp production, from softwood, unblea...","sawdust, wet, measured as dry mass",RER,3928: Sawdust and wood waste and scrap,None,"1701:Manufacture of pulp, paper and paperboard",2.843601e-08,3.0,8.530802e-08
...,...,...,...,...,...,...,...,...,...,...,...
1223,"Carbon dioxide, fossil","(air, urban air close to ground)","carbon dioxide production, liquid","carbon dioxide, liquid",RER,"34210: Hydrogen, nitrogen, oxygen, carbon diox...",None,2011:Manufacture of basic chemicals,2.421657e-07,3.0,7.264970e-07
1224,"Carbon dioxide, fossil","(air, urban air close to ground)","transport, passenger car, large size, diesel, ...","transport, passenger car, large size, diesel, ...",RER,64119: Other land transportation services of p...,None,4922:Other passenger land transport,1.206713e-05,3.0,3.620138e-05
1225,"Carbon dioxide, fossil","(air, urban air close to ground)",silicon carbide production,silicon carbide,RER,34280: Hydrogen peroxide; phosphides; carbides...,None,2391:Manufacture of refractory products,1.185752e-06,3.0,3.557255e-06
1226,"Carbon dioxide, fossil","(air, urban air close to ground)","formic acid production, methyl formate route",formic acid,RER,34120: Industrial monocarboxylic fatty acids; ...,None,2011:Manufacture of basic chemicals,9.551826e-11,3.0,2.865548e-10
1227,"Carbon dioxide, fossil","(air, urban air close to ground)","treatment of used capacitor, to hazardous wast...",used capacitor,CH,39990: Other wastes n.e.c.,None,3822:Treatment and disposal of hazardous waste,7.169261e-16,1.0,7.169261e-16

As expected, only CH, FR and RER-based consumers have been considered in the calculation.

In [10]:
df.groupby("consumer location")["CF"].mean()

consumer location
CA     15.0
CH      1.0
FR      2.0
RER     3.0
Name: CF, dtype: float64

But `statistics()` tells us that many exchanges have been ignored.

In [11]:
LCA.statistics()

+----------------------+---------------------------------------+
|       Activity       |  copper production, cathode, solvent  |
|                      | extraction and electrowinning process |
|     Method name      |           ('some', 'method')          |
|         Unit         |                kg CO2e                |
|      Data file       |             lcia_example_2            |
|    CFs in method     |                   4                   |
|       CFs used       |                  1228                 |
|   Unique CFs used    |                   4                   |
|  Exc. characterized  |                  1228                 |
| Exc. uncharacterized |                 334784                |
+----------------------+---------------------------------------+

We can extend the application of CFs to other exchanges, using the helping functions: `map_aggregate_locations`, `map_disaggregate_location`, `map_dynamic_locations` and `map_remaining_locations_to_global`.

* `map_aggregate_locations` maps exchanges with aggregate locations (e.g., "RER", RLA", etc.) to weighted-average CFs.
* `map_disaggregate_location` maps exchanges with locations that belong to aggregate locations ("CA-QC") to CFs of aggregate locations (e.g., "CA").
* `map_dynamic_locations` maps exchanges with dynamic locations (e.g., "RoW", "RoW") to CFs calculated as the weighted-average of all locations minus those excluded by dynamic locations' perimeter (e.g., "GLO minus CH").
* `map_remaining_locations_to_global` maps exchanges with remaining locations to the global CFs.

In [ ]:
LCA = EdgeLCIA(
    demand={act: 1},
    method=("some", "method"),
    filepath="lcia_example_2.json"
)
LCA.lci()

LCA.map_exchanges()

LCA.map_aggregate_locations()
LCA.map_dynamic_locations()
LCA.map_contained_locations()
LCA.map_remaining_locations_to_global()

LCA.evaluate_cfs()
LCA.lcia()
LCA.score

map contained locations starts
running find_locations for IE
finished find_locations
IE -> nearest is : RER
running find_locations for RNA
finished find_locations
RNA -> nearest is None
running find_locations for CN
finished find_locations
CN -> nearest is None
running find_locations for BR
finished find_locations
BR -> nearest is None
running find_locations for ID
finished find_locations
ID -> nearest is None
running find_locations for US
finished find_locations
US -> nearest is None
running find_locations for GLO
finished find_locations
GLO -> nearest is None
running find_locations for AZ
finished find_locations
AZ -> nearest is None
running find_locations for IN-HR
finished find_locations
IN-HR -> nearest is None
running find_locations for IN-MH
finished find_locations
IN-MH -> nearest is None
running find_locations for Europe without Switzerland
finished find_locations
Europe without Switzerland -> nearest is : RER
running find_locations for IN-UT
finished find_locations
IN-UT -> nearest is None
running find_locations for ES
finished find_locations
ES -> nearest is : RER
running find_locations for AU-SA
finished find_locations
AU-SA -> nearest is None
running find_locations for AU-VIC
finished find_locations
AU-VIC -> nearest is None
running find_locations for US-RFC
finished find_locations
US-RFC -> nearest is None
running find_locations for IT
finished find_locations
IT -> nearest is : RER
running find_locations for CN-HL
finished find_locations
CN-HL -> nearest is None
running find_locations for FI
finished find_locations
FI -> nearest is : RER
running find_locations for GR
finished find_locations
GR -> nearest is : RER
running find_locations for CA-YK
finished find_locations
CA-YK -> nearest is : CA
running find_locations for NL
finished find_locations
NL -> nearest is : RER
running find_locations for CO
finished find_locations
CO -> nearest is None
running find_locations for CA-NS
finished find_locations
CA-NS -> nearest is : CA
running find_locations for BR-North-eastern grid
finished find_locations
BR-North-eastern grid -> nearest is None
running find_locations for DE
finished find_locations
DE -> nearest is : RER
running find_locations for IN-MN
finished find_locations
IN-MN -> nearest is None
running find_locations for BR-TO
finished find_locations
BR-TO -> nearest is None
running find_locations for RLA
finished find_locations
RLA -> nearest is None
running find_locations for RU
finished find_locations
RU -> nearest is None
running find_locations for TH
finished find_locations
TH -> nearest is None
running find_locations for GB
finished find_locations
GB -> nearest is : RER
running find_locations for ZA
finished find_locations
ZA -> nearest is None
running find_locations for CN-SC
finished find_locations
CN-SC -> nearest is None
running find_locations for US-TRE
finished find_locations
US-TRE -> nearest is None
running find_locations for AU-NSW
finished find_locations
AU-NSW -> nearest is None
running find_locations for CA-QC
finished find_locations
CA-QC -> nearest is : CA
running find_locations for MX
finished find_locations
MX -> nearest is None
running find_locations for TT
finished find_locations
TT -> nearest is None
running find_locations for Europe without Switzerland and Austria
finished find_locations
Europe without Switzerland and Austria -> nearest is : RER
running find_locations for IN-JH
finished find_locations
IN-JH -> nearest is None
running find_locations for NO
finished find_locations
NO -> nearest is : RER
running find_locations for CN-ZJ
finished find_locations
CN-ZJ -> nearest is None
running find_locations for BR-RS
finished find_locations
BR-RS -> nearest is None
running find_locations for CM
finished find_locations
CM -> nearest is None
running find_locations for BR-MG
finished find_locations
BR-MG -> nearest is None
running find_locations for AT
finished find_locations
AT -> nearest is : RER
running find_locations for RS
finished find_locations
RS -> nearest is : RER
running find_locations for CN-GX
finished find_locations
CN-GX -> nearest is None
running find_locations for PH
finished find_locations
PH -> nearest is None
running find_locations for AU-QLD
finished find_locations
AU-QLD -> nearest is None
running find_locations for US-MN
finished find_locations
US-MN -> nearest is None
running find_locations for CZ
finished find_locations
CZ -> nearest is : RER
running find_locations for CN-JS
finished find_locations
CN-JS -> nearest is None
running find_locations for IN-TR
finished find_locations
IN-TR -> nearest is None
running find_locations for CN-FJ
finished find_locations
CN-FJ -> nearest is None
running find_locations for AU
finished find_locations
AU -> nearest is None
running find_locations for BG
finished find_locations
BG -> nearest is : RER
running find_locations for BR-PI
finished find_locations
BR-PI -> nearest is None
running find_locations for CN-TJ
finished find_locations
CN-TJ -> nearest is None
running find_locations for CN-XJ
finished find_locations
CN-XJ -> nearest is None
running find_locations for LU
finished find_locations
LU -> nearest is : RER
running find_locations for US-ASCC
finished find_locations
US-ASCC -> nearest is None
running find_locations for BR-PR
finished find_locations
BR-PR -> nearest is None
running find_locations for CN-JX
finished find_locations
CN-JX -> nearest is None
running find_locations for BE
finished find_locations
BE -> nearest is : RER
running find_locations for MY
finished find_locations
MY -> nearest is None
running find_locations for TR
finished find_locations
TR -> nearest is None
running find_locations for SK
finished find_locations
SK -> nearest is : RER
running find_locations for BR-Northern grid
finished find_locations
BR-Northern grid -> nearest is None
running find_locations for AR
finished find_locations
AR -> nearest is None
running find_locations for RO
finished find_locations
RO -> nearest is : RER
running find_locations for CA-MB
finished find_locations
CA-MB -> nearest is : CA
running find_locations for SI
finished find_locations
SI -> nearest is : RER
running find_locations for BR-MA
finished find_locations
BR-MA -> nearest is None
running find_locations for BR-South-eastern/Mid-western grid
finished find_locations
BR-South-eastern/Mid-western grid -> nearest is None
running find_locations for IN
finished find_locations
IN -> nearest is None
running find_locations for US-MRO
finished find_locations
US-MRO -> nearest is None
running find_locations for IN-UP
finished find_locations
IN-UP -> nearest is None
running find_locations for HU
finished find_locations
HU -> nearest is : RER
running find_locations for IR
finished find_locations
IR -> nearest is None
running find_locations for CA-BC
finished find_locations
CA-BC -> nearest is : CA
running find_locations for CA-NT
finished find_locations
CA-NT -> nearest is : CA
running find_locations for BR-SP
finished find_locations
BR-SP -> nearest is None
running find_locations for NP
finished find_locations
NP -> nearest is None
running find_locations for PL
finished find_locations
PL -> nearest is : RER
running find_locations for BR-MS
finished find_locations
BR-MS -> nearest is None
running find_locations for TW
finished find_locations
TW -> nearest is None
running find_locations for US-WECC
finished find_locations
US-WECC -> nearest is None
running find_locations for KZ
finished find_locations
KZ -> nearest is None
running find_locations for CN-SH
finished find_locations
CN-SH -> nearest is None
running find_locations for SE
finished find_locations
SE -> nearest is : RER
running find_locations for IN-Northern grid
finished find_locations
IN-Northern grid -> nearest is None
running find_locations for US-SERC
finished find_locations
US-SERC -> nearest is None
running find_locations for UA
finished find_locations
UA -> nearest is : RER
running find_locations for JP
finished find_locations
JP -> nearest is None
running find_locations for IN-RJ
finished find_locations
IN-RJ -> nearest is None
running find_locations for US-CO
finished find_locations
US-CO -> nearest is None
running find_locations for DK
finished find_locations
DK -> nearest is : RER
running find_locations for US-NPCC
finished find_locations
US-NPCC -> nearest is None
running find_locations for IN-MP
finished find_locations
IN-MP -> nearest is None
running find_locations for CN-QH
finished find_locations
CN-QH -> nearest is None
running find_locations for BR-GO
finished find_locations
BR-GO -> nearest is None
running find_locations for CN-GS
finished find_locations
CN-GS -> nearest is None
running find_locations for IN-WB
finished find_locations
IN-WB -> nearest is None
running find_locations for KR
finished find_locations
KR -> nearest is None
running find_locations for SA
finished find_locations
SA -> nearest is None
running find_locations for BR-MT
finished find_locations
BR-MT -> nearest is None
running find_locations for IS
finished find_locations
IS -> nearest is : RER
running find_locations for CN-BJ
finished find_locations
CN-BJ -> nearest is None
running find_locations for IN-DL
finished find_locations
IN-DL -> nearest is None
running find_locations for PT
finished find_locations
PT -> nearest is : RER
running find_locations for US-OR
finished find_locations
US-OR -> nearest is None
running find_locations for CN-AH
finished find_locations
CN-AH -> nearest is None
running find_locations for PE
finished find_locations
PE -> nearest is None
running find_locations for CA-SK
finished find_locations
CA-SK -> nearest is : CA
running find_locations for CN-HA
finished find_locations
CN-HA -> nearest is None
running find_locations for IN-KA
finished find_locations
IN-KA -> nearest is None
running find_locations for IN-PB
finished find_locations
IN-PB -> nearest is None
running find_locations for HR
finished find_locations
HR -> nearest is : RER
running find_locations for US-HICC
finished find_locations
US-HICC -> nearest is None
running find_locations for CN-XZ
finished find_locations
CN-XZ -> nearest is None
running find_locations for US-IL
finished find_locations
US-IL -> nearest is None
running find_locations for IN-CT
finished find_locations
IN-CT -> nearest is None
running find_locations for UZ
finished find_locations
UZ -> nearest is None
running find_locations for MK
finished find_locations
MK -> nearest is : RER
running find_locations for IN-GA
finished find_locations
IN-GA -> nearest is None
running find_locations for US-ND
finished find_locations
US-ND -> nearest is None
running find_locations for TZ
finished find_locations
TZ -> nearest is None
running find_locations for US-NE
finished find_locations
US-NE -> nearest is None
running find_locations for US-IN
finished find_locations
US-IN -> nearest is None
running find_locations for AE
finished find_locations
AE -> nearest is None
running find_locations for Canada without Quebec
finished find_locations
Canada without Quebec -> nearest is : CA
running find_locations for TM
finished find_locations
TM -> nearest is None
running find_locations for US-WI
finished find_locations
US-WI -> nearest is None
running find_locations for IN-AP
finished find_locations
IN-AP -> nearest is None
running find_locations for MT
finished find_locations
MT -> nearest is : RER
running find_locations for LT
finished find_locations
LT -> nearest is : RER
running find_locations for VN
finished find_locations
VN -> nearest is None
running find_locations for AU-TAS
finished find_locations
AU-TAS -> nearest is None
running find_locations for EC
finished find_locations
EC -> nearest is None
running find_locations for CN-SA
finished find_locations
CN-SA -> nearest is None
running find_locations for BO
finished find_locations
BO -> nearest is None
running find_locations for AU-WA
finished find_locations
AU-WA -> nearest is None
running find_locations for IN-TN
finished find_locations
IN-TN -> nearest is None
running find_locations for CL
finished find_locations
CL -> nearest is None
running find_locations for IN-ML
finished find_locations
IN-ML -> nearest is None
running find_locations for CN-HE
finished find_locations
CN-HE -> nearest is None
running find_locations for BR-BA
finished find_locations
BR-BA -> nearest is None
running find_locations for IN-SK
finished find_locations
IN-SK -> nearest is None
running find_locations for IN-Southern grid
finished find_locations
IN-Southern grid -> nearest is None
running find_locations for IN-MZ
finished find_locations
IN-MZ -> nearest is None
running find_locations for BD
finished find_locations
BD -> nearest is None
running find_locations for CA-ON
finished find_locations
CA-ON -> nearest is : CA
running find_locations for CA
finished find_locations
CA -> nearest is None
running find_locations for IN-GJ
finished find_locations
IN-GJ -> nearest is None
running find_locations for IN-HP
finished find_locations
IN-HP -> nearest is None
running find_locations for CN-JL
finished find_locations
CN-JL -> nearest is None
running find_locations for CN-SD
finished find_locations
CN-SD -> nearest is None
running find_locations for US-WA
finished find_locations
US-WA -> nearest is None
running find_locations for CN-NX
finished find_locations
CN-NX -> nearest is None
running find_locations for BA
finished find_locations
BA -> nearest is : RER
running find_locations for IN-AS
finished find_locations
IN-AS -> nearest is None
running find_locations for CN-LN
finished find_locations
CN-LN -> nearest is None
running find_locations for CN-HU
finished find_locations
CN-HU -> nearest is None
running find_locations for CN-NM
finished find_locations
CN-NM -> nearest is None
running find_locations for EE
finished find_locations
EE -> nearest is : RER
running find_locations for CN-GD
finished find_locations
CN-GD -> nearest is None
running find_locations for IN-JK
finished find_locations
IN-JK -> nearest is None
running find_locations for IN-PY
finished find_locations
IN-PY -> nearest is None
running find_locations for OM
finished find_locations
OM -> nearest is None
running find_locations for CA-AB
finished find_locations
CA-AB -> nearest is : CA
running find_locations for LV
finished find_locations
LV -> nearest is : RER
running find_locations for IN-Eastern grid
finished find_locations
IN-Eastern grid -> nearest is None
running find_locations for CA-NB
finished find_locations
CA-NB -> nearest is : CA
running find_locations for CN-CQ
finished find_locations
CN-CQ -> nearest is None
running find_locations for DZ
finished find_locations
DZ -> nearest is None
running find_locations for BR-Southern grid
finished find_locations
BR-Southern grid -> nearest is None
running find_locations for IN-OR
finished find_locations
IN-OR -> nearest is None
running find_locations for IN-North-eastern grid
finished find_locations
IN-North-eastern grid -> nearest is None
running find_locations for CN-YN
finished find_locations
CN-YN -> nearest is None
running find_locations for EG
finished find_locations
EG -> nearest is None
running find_locations for LY
finished find_locations
LY -> nearest is None
running find_locations for IN-KL
finished find_locations
IN-KL -> nearest is None
running find_locations for IN-NL
finished find_locations
IN-NL -> nearest is None
running find_locations for CA-NF
finished find_locations
CA-NF -> nearest is : CA
running find_locations for UN-SEASIA
finished find_locations
UN-SEASIA -> nearest is None
running find_locations for VE
finished find_locations
VE -> nearest is None
running find_locations for IAI Area, Russia & RER w/o EU27 & EFTA
finished find_locations
IAI Area, Russia & RER w/o EU27 & EFTA -> nearest is None
running find_locations for IAI Area, South America
finished find_locations
IAI Area, South America -> nearest is None
running find_locations for CA-NU
finished find_locations
CA-NU -> nearest is : CA
running find_locations for NG
finished find_locations
NG -> nearest is None
running find_locations for KW
finished find_locations
KW -> nearest is None
running find_locations for CN-HN
finished find_locations
CN-HN -> nearest is None
running find_locations for IAI Area, EU27 & EFTA
finished find_locations
IAI Area, EU27 & EFTA -> nearest is : RER
running find_locations for CA-PE
finished find_locations
CA-PE -> nearest is : CA
running find_locations for TN
finished find_locations
TN -> nearest is None
running find_locations for US-IA
finished find_locations
US-IA -> nearest is None
running find_locations for PG
finished find_locations
PG -> nearest is None
running find_locations for CN-SX
finished find_locations
CN-SX -> nearest is None
running find_locations for IN-DN
finished find_locations
IN-DN -> nearest is None
running find_locations for US-ID
finished find_locations
US-ID -> nearest is None
running find_locations for CN-HB
finished find_locations
CN-HB -> nearest is None
running find_locations for SAS
finished find_locations
SAS -> nearest is None
running find_locations for US-OH
finished find_locations
US-OH -> nearest is None
running find_locations for CY
finished find_locations
CY -> nearest is None
running find_locations for ZM
finished find_locations
ZM -> nearest is None
running find_locations for US-SD
finished find_locations
US-SD -> nearest is None
running find_locations for IN-BR
finished find_locations
IN-BR -> nearest is None
running find_locations for MA
finished find_locations
MA -> nearest is None
running find_locations for WEU
finished find_locations
WEU -> nearest is : RER
running find_locations for IAI Area, Gulf Cooperation Council
finished find_locations
IAI Area, Gulf Cooperation Council -> nearest is None
running find_locations for QA
finished find_locations
QA -> nearest is None
running find_locations for CN-GZ
finished find_locations
CN-GZ -> nearest is None
running find_locations for IQ
finished find_locations
IQ -> nearest is None
running find_locations for UN-OCEANIA
finished find_locations
UN-OCEANIA -> nearest is None
running find_locations for IAI Area, Africa
finished find_locations
IAI Area, Africa -> nearest is None
running find_locations for IAI Area, Asia, without China and GCC
finished find_locations
IAI Area, Asia, without China and GCC -> nearest is None
running find_locations for RAF
finished find_locations
RAF -> nearest is None
running find_locations for RER w/o DE+NL+RU
finished find_locations
RER w/o DE+NL+RU -> nearest is : RER
running find_locations for RER w/o RU
finished find_locations
RER w/o RU -> nearest is : RER
running find_locations for IN-Western grid
finished find_locations
IN-Western grid -> nearest is None
(('name', 'Carbon dioxide, fossil'),) (1.0000 * (3.0)) {'name': 'Carbon dioxide, fossil'} {'location': 'IE', 'classifications': [('EcoSpold01Categories', 'oil/power plants'), ('ISIC rev.4 ecoinvent', '3510:Electric power generation, transmission and distribution'), ('CPC', '17100: Electrical energy')]} ['__ANY__'] ['RER']

12.828075349786848

In [23]:
LCA.statistics()

+----------------------+---------------------------------------+
|       Activity       |  copper production, cathode, solvent  |
|                      | extraction and electrowinning process |
|     Method name      |           ('some', 'method')          |
|         Unit         |                kg CO2e                |
|      Data file       |             lcia_example_2            |
|    CFs in method     |                   4                   |
|       CFs used       |                  6464                 |
|   Unique CFs used    |                   6                   |
|  Exc. characterized  |                  6464                 |
| Exc. uncharacterized |                 329548                |
+----------------------+---------------------------------------+

In [24]:
LCA.weights

{('__ANY__', 'CH'): 8921981.0,
 ('__ANY__', 'FR'): 66548530.0,
 ('__ANY__', 'RER'): 0.0,
 ('__ANY__', 'CA'): 39742430.0}

In [25]:
df = LCA.generate_cf_table(split_aggregate_consumers=True)

In [26]:
df.loc[df["consumer location"]=="CA-NF"]

,supplier name,supplier categories,consumer name,consumer reference product,consumer location,consumer cpc,consumer ecospold01categories,consumer isic rev.4 ecoinvent,amount,CF,impact
2001,"Carbon dioxide, fossil","(air, urban air close to ground)","electricity production, oil","electricity, high voltage",CA-NF,17100: Electrical energy,oil/power plants,"3510:Electric power generation, transmission a...",2.998160e-05,3.0000,8.994481e-05
2002,"Carbon dioxide, fossil","(air,)","electricity production, oil","electricity, high voltage",CA-NF,17100: Electrical energy,oil/power plants,"3510:Electric power generation, transmission a...",2.368450e-07,3.0000,7.105351e-07
3946,"Carbon dioxide, from soil or biomass stock","(air, non-urban air or from high stacks)","electricity production, hydro, reservoir, non-...","electricity, high voltage",CA-NF,17100: Electrical energy,None,"3510:Electric power generation, transmission a...",2.730917e-04,1.8818,5.139040e-04

In [16]:
df.loc[df["consumer location"]=="CA-NF"]

,supplier name,supplier categories,consumer name,consumer reference product,consumer location,consumer cpc,consumer ecospold01categories,consumer isic rev.4 ecoinvent,amount,CF,impact
2415,"Carbon dioxide, fossil","(air, urban air close to ground)","electricity production, oil","electricity, high voltage",CA-NF,17100: Electrical energy,oil/power plants,"3510:Electric power generation, transmission a...",2.998160e-05,15.0,0.000450
2416,"Carbon dioxide, fossil","(air,)","electricity production, oil","electricity, high voltage",CA-NF,17100: Electrical energy,oil/power plants,"3510:Electric power generation, transmission a...",2.368450e-07,15.0,0.000004
2417,"Carbon dioxide, from soil or biomass stock","(air, non-urban air or from high stacks)","electricity production, hydro, reservoir, non-...","electricity, high voltage",CA-NF,17100: Electrical energy,None,"3510:Electric power generation, transmission a...",2.730917e-04,15.0,0.004096

We can check the weights used:

In [ ]:
LCA.weights

By default, if weights are not provided in the consumer sections of LCIA file, population is used. The other option is GDP. To be specified when calling EdgeLICA().

And we can see the weighted-average CFs used:

In [ ]:
df.groupby("consumer location")["CF"].mean()

We have pre-generated LCIA files for specific methods (AWARE, ImpactWorld+, etc.).
You can get a list like so:

In [ ]:
get_available_methods()

Check the other notebooks to see how to use them.